### ISSUE TITLE
Sprint: Oct 31 → Nov 6

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#236] opened 2016-10-26 16:18 UTC
# Halloween Sprint

_For information about these calls and how they work, read [the ipfs/pm README](https://github.com/ipfs/pm)._

[Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com)

Zoom and Stream links will be updated directly before the calls. Links to them will also be dropped in IRC, at the start of each call. If the link below seems to link to this issue, the link has not been updated yet.

| Endeavour | Lead | Time (**UTC/Z**) | Zoom | Stream | Pad |
| :-: | :-: | :-: | :-: | :-: | :-: |
| All Hands Call | @flyingzumwalt | **16:00Z** | [Zoom](https://zoom.us/j/3339991818) | [Stream](https://www.youtube.com/watch?v=ac-OdiFndec) | [notes](https://public.etherpad-mozilla.org/p/ipfs-oct-31-all-hands) |
| go-ipfs | @whyrusleeping |**17:00Z** | [Zoom](https://zoom.us/j/3339991818) | [Stream](https://www.youtube.com/watch?v=ac-OdiFndec) | [notes](https://public.etherpad-mozilla.org/p/ipfs-oct-31-go-ipfs) |
| js-ipfs | @diasdavid |  **17:30Z** | [Zoom](https://zoom.us/j/3339991818) | [Stream](https://www.youtube.com/watch?v=ac-OdiFndec) | [notes](https://public.etherpad-mozilla.org/p/ipfs-oct-31-js-ipfs) |
| libp2p | @diasdavid | **18:00Z** | [Zoom](https://zoom.us/j/3339991818) | [Stream](https://www.youtube.com/watch?v=ac-OdiFndec) | [notes](https://public.etherpad-mozilla.org/p/ipfs-oct-31-libp2p) |
| IPLD | @nicola | **18:30Z**| [Zoom](https://zoom.us/j/3339991818) | [Stream](https://www.youtube.com/watch?v=ac-OdiFndec) | [notes](https://public.etherpad-mozilla.org/p/ipfs-oct-31-ipld) |

Please add any agenda items you have to the pad before the project-specific sprint call starts.

**Comment by parkan** [comment] 2016-10-27 20:47
Hi @RichardLitt, we have a few follow-up things to discuss in the wake of our [1.0 launch](https://blog.mediachain.io/mediachain-v1-0-be2b8fa2153) -- let me know if we can squeeze any of these in 😄 

* mediachain prefix for multiaddr -- should I just PR against https://github.com/multiformats/multiaddr/blob/master/protocols.csv? Should it be `mc/$peerId` or `secIo/$peerId/mc`? (would prefer the former for consistency with ipfs and possibility of moving to diff peerId scheme)
* intermittent context deadline exceeded error (libp2p/go-libp2p#138)
* potential concerns about HOL blocking/other performance limitations w/multistream
* design questions about [go-datastore](https://github.com/ipfs/go-datastore) -- we want to wrap our rocksdb datastore in this to make object storage compatible w/IPFS but the interface seems quite heavyweight, need some guidance on how to conform

**Comment by kevina** [comment] 2016-10-27 21:27
> design questions about go-datastore -- we want to wrap our rocksdb datastore in this to make object storage compatible w/IPFS but the interface seems quite heavyweight, need some guidance on how to conform

If all you are interested in is storing blocks I would look at [ipfs/go-ds-flatfs](https://github.com/ipfs/go-ds-flatfs).  In particular you don't really need to worry about implementing the query method properly, just do what is done in flatfs (and what I do in the filestore).

**Comment by parkan** [comment] 2016-10-27 23:11
@kevina can you walk me through the semantics of `Query`? I'm having a bit of trouble figuring out what the intended behavior is and how it's used.

**Comment by parkan** [comment] 2016-10-27 23:12
@kevina ok apparently it's been a long day because I did not register the second part of your comment at all! My question still stands -- I'm concerned in part because in our case rocksdb is specifically tuned for point lookups and *not* scans.

**Comment by whyrusleeping** [comment] 2016-10-27 23:22
Hey @arkadiy, if you want to we can have a video chat soon (maybe
tomorrow?) And discuss things :)

**Comment by kevina** [comment] 2016-10-27 23:31
@parkan all that is really needed to some how be able to get all the keys, maybe @whyrusleeping can help you, I might be able to, but let's take this off line, ping me on IRC or just email me at k@kevina.org.

**Comment by parkan** [comment] 2016-10-28 21:52
@whyrusleeping down to chat, sorry saw this too late to chat today -- how about early next week?

**Comment by RichardLitt** [comment] 2016-10-29 14:24
Hey @parkan, sorry for the delay! 

> mediachain prefix for multiaddr -- should I just PR against https://github.com/multiformats/multiaddr/blob/master/protocols.csv? Should it be mc/$peerId or secIo/$peerId/mc? (would prefer the former for consistency with ipfs and possibility of moving to diff peerId scheme)

I would open an issue on multiaddr for this; I don't know the answer to your second question, but we should be able to discuss it there. Regarding your other questions, I think @whyrusleeping is probably the best person to help. 

Might be best to add these notes to the agenda for Monday's All hands, and we can cover how to follow up with them there?

**Comment by diasdavid** [comment] 2016-10-30 11:59
> mediachain prefix for multiaddr -- should I just PR against https://github.com/multiformats/multiaddr/blob/master/protocols.csv? Should it be mc/$peerId or secIo/$peerId/mc? (would prefer the former for consistency with ipfs and possibility of moving to diff peerId scheme)

What are you trying to achieve with a mediachain multiaddr? Is there a mediachain specific transport? Shouldn't that be a Protocol that gets Stream Muxed with multistream?

**Comment by flyingzumwalt** [comment] 2016-10-31 01:46
@RichardLitt @haadcode didn't we decide that, starting this week, we would be adding a call for orbit and general distributed apps work?  I remember a conversation about adding that to the default template.

**Comment by haadcode** [comment] 2016-10-31 06:18
@flyingzumwalt I won't be back until tomorrow and won't be able to attend nor lead the app meeting this week, so the original plan was to start it next week. However, I don't see why we couldn't start it this week if someone else can lead it.

**Comment by parkan** [comment] 2016-10-31 16:05
@diasdavid those seem like good semantics too -- where should I take this discussion?

**Comment by RichardLitt** [comment] 2016-11-01 12:31
@parkan github.com/multiformats/multiaddr would be fine. :)

**Closed** 2016-11-08 11:55 UTC
